name: C++ Build and Run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install Clang
      shell: bash
      run: sudo apt install clang
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: build
      shell: bash
      run: for d in $(find $GITHUB_WORKSPACE/*/* -maxdepth 1 -type d); do clang++ $d/*.cpp -o $d/test_build -std=c++17 -Werror; done;
  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: run
      shell: bash
      run: for d in $(find $GITHUB_WORKSPACE/*/* -maxdepth 1 -type d); do $d/test_build; done;
